version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC & G++
          command: 'sudo apt-get -y update && apt-get install -y gcc g++'
      - run:
          name: Installing libgtkmm-3.0-dev
          command: 'sudo apt-get -y install libgtkmm-3.0-dev'
      - run:
          name: Installing libgtksourceviewmm-3.0-dev
          command: 'sudo apt-get -y install libgtksourceviewmm-3.0-dev'
      - run:
          name: Creating Build Files
          command: 'make'
      
