version: 2.1

jobs:
  build:
    docker:
      - image: "debian:stretch"
    steps:
      - checkout
      - run:
          name: Installing libgtkmm-3.0-dev
          command: 'sudo apt-get install libgtkmm-3.0-dev'
      - run:
          name: Installing libgtksourceviewmm-3.0-dev
          command: 'sudo apt-get install libgtksourceviewmm-3.0-dev'
      - run:
          name: Creating Build Files
          command: 'make'
      
