version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo'
      - run:
          name: Installing GCC & G++
          command: 'sudo apt-get update -y && sudo apt-get install g++-11 -y'
      - run:
          name: Installing libgtkmm-3.0-dev
          command: 'sudo apt-get -y install libgtkmm-3.0-dev'
      - run:
          name: Installing libgtksourceviewmm-3.0-dev
          command: 'sudo apt-get -y install libgtksourceviewmm-3.0-dev'
      - run:
          name: Creating Build Files
          command: 'mkdir build && make'
      
